#!/usr/bin/env bash

if [[ -n "${DEXJOCO_COMMON_ENV_SH_LOADED:-}" ]]; then
  return 0
fi
export DEXJOCO_COMMON_ENV_SH_LOADED=1

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export DEXJOCO_ROOT="${DEXJOCO_ROOT:-${ROOT_DIR}}"
export DEXJOCO_ENV_PREFIX="${DEXJOCO_ENV_PREFIX:-${DEXJOCO_ROOT}/.conda/dexjoco}"
export PI05_ROOT="${PI05_ROOT:-/nfs_global/S/yangrongzheng/pi05}"
export OPENPI_ENV_PREFIX="${OPENPI_ENV_PREFIX:-${PI05_ROOT}/.conda-pi05-openpi-final}"
export CLEAN_OPENPI_ENV_PREFIX="${CLEAN_OPENPI_ENV_PREFIX:-${DEXJOCO_ROOT}/.conda/openpi}"

export DEXJOCO_OPENPI_SRC="${DEXJOCO_OPENPI_SRC:-${DEXJOCO_ROOT}/openpi/src}"
export DEXJOCO_OPENPI_CLIENT_SRC="${DEXJOCO_OPENPI_CLIENT_SRC:-${DEXJOCO_ROOT}/openpi/packages/openpi-client/src}"
export DEXJOCO_CLEAN_PYTHONPATH_DEFAULT="${DEXJOCO_OPENPI_SRC}:${DEXJOCO_OPENPI_CLIENT_SRC}"
export DEXJOCO_STRIP_PYTHONPATH="${DEXJOCO_STRIP_PYTHONPATH:-1}"
export PI05_USE_CLEAN_OPENPI_ENV="${PI05_USE_CLEAN_OPENPI_ENV:-0}"

if [[ "${PI05_USE_CLEAN_OPENPI_ENV}" == "1" ]]; then
  export PI05_EFFECTIVE_OPENPI_ENV_PREFIX="${PI05_EFFECTIVE_OPENPI_ENV_PREFIX:-${CLEAN_OPENPI_ENV_PREFIX}}"
else
  export PI05_EFFECTIVE_OPENPI_ENV_PREFIX="${PI05_EFFECTIVE_OPENPI_ENV_PREFIX:-${OPENPI_ENV_PREFIX}}"
fi

export OPENPI_PRETRAINED_MODEL_PATH="${OPENPI_PRETRAINED_MODEL_PATH:-${PI05_ROOT}/openpi_official/checkpoints/pi05_droid/params}"
export OPENPI_PRETRAINED_MODEL_ACTION_DIM_44_PATH="${OPENPI_PRETRAINED_MODEL_ACTION_DIM_44_PATH:-${DEXJOCO_ROOT}/checkpoints/pi05_base_action_dim_44/params}"
export OPENPI_DATASET_ROOT="${OPENPI_DATASET_ROOT:-${DEXJOCO_ROOT}/datasets/dexjoco_lerobot_datasets}"
export OPENPI_RAND_FULL_DATASET_ROOT="${OPENPI_RAND_FULL_DATASET_ROOT:-${DEXJOCO_ROOT}/datasets/dexjoco_lerobot_datasets_rand_full}"
export OPENPI_CKPTS_ROOT="${OPENPI_CKPTS_ROOT:-${DEXJOCO_ROOT}/checkpoints/pi05_ckpts}"
export OPENPI_RAND_FULL_CKPTS_ROOT="${OPENPI_RAND_FULL_CKPTS_ROOT:-${DEXJOCO_ROOT}/checkpoints/pi05_rand_full_ckpts}"

export PI05_SERVER_PORT="${PI05_SERVER_PORT:-8000}"
export PI05_SERVER_HOST="${PI05_SERVER_HOST:-0.0.0.0}"
export PI05_TASK="${PI05_TASK:-water_plant}"
export PI05_CONFIG_SET="${PI05_CONFIG_SET:-rand_obj}"
export PI05_SEED="${PI05_SEED:-0}"
export PI05_EPISODES="${PI05_EPISODES:-50}"
export PI05_CUDA_VISIBLE_DEVICES="${PI05_CUDA_VISIBLE_DEVICES:-0}"
export PI05_XLA_MEM_FRACTION="${PI05_XLA_MEM_FRACTION:-0.4}"

if [[ "${PI05_CONFIG_SET}" == "rand_full" ]]; then
  export PI05_POLICY_CONFIG="${PI05_POLICY_CONFIG:-${PI05_TASK}_rand_full}"
  export PI05_TASK_CONFIG="${PI05_TASK_CONFIG:-${DEXJOCO_ROOT}/configs/rand_full/${PI05_TASK}.yaml}"
  export PI05_POLICY_DIR="${PI05_POLICY_DIR:-${OPENPI_RAND_FULL_CKPTS_ROOT}/${PI05_TASK}_rand_full}"
else
  export PI05_POLICY_CONFIG="${PI05_POLICY_CONFIG:-${PI05_TASK}}"
  export PI05_TASK_CONFIG="${PI05_TASK_CONFIG:-${DEXJOCO_ROOT}/configs/rand_obj/${PI05_TASK}.yaml}"
  export PI05_POLICY_DIR="${PI05_POLICY_DIR:-${OPENPI_CKPTS_ROOT}/${PI05_TASK}}"
fi

mkdir -p \
  "${DEXJOCO_ROOT}/checkpoints" \
  "${DEXJOCO_ROOT}/datasets" \
  "${OPENPI_CKPTS_ROOT}" \
  "${OPENPI_RAND_FULL_CKPTS_ROOT}"
